---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: couchbase-prod

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: couchbase
      app.kubernetes.io/component: database
      app.kubernetes.io/managed-by: argocd
      environment: prod
