---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: couchbase-pods
  namespace: couchbase
  labels:
    app: couchbase
spec:
  selector:
    matchLabels:
      app: couchbase
  podMetricsEndpoints:
    - port: metrics
      interval: 30s
      path: /metrics
      scheme: http
      scrapeTimeout: 25s
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_name]
          targetLabel: instance
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: node
        - sourceLabels: [__meta_kubernetes_namespace]
          targetLabel: namespace
        - sourceLabels: [__meta_kubernetes_pod_label_couchbase_cluster]
          targetLabel: couchbase_cluster
        - sourceLabels: [__meta_kubernetes_pod_label_couchbase_server]
          targetLabel: server_group
        - sourceLabels: [__meta_kubernetes_pod_container_name]
          targetLabel: container
      metricRelabelings:
        - sourceLabels: [__name__]
          regex: 'couchbase_.*|sys_.*|bucket_.*|index_.*|query_.*|xdcr_.*'
          action: keep
        - sourceLabels: [bucket]
          regex: ''
          action: drop
