---
# Kustomization file for the cluster deployment
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: couchbase

resources:
  - namespace.yaml
  - cluster.yaml
  - buckets.yaml
  - users.yaml
  - replication.yaml
  - network-policy.yaml
  - ingress.yaml
  - resource-limits.yaml

commonLabels:
  app.kubernetes.io/name: couchbase
  app.kubernetes.io/component: database
  app.kubernetes.io/managed-by: argocd
