---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-thanos

---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-thanos-token
  annotations:
    kubernetes.io/service-account.name: grafana-thanos
type: kubernetes.io/service-account-token

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-thanos-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-monitoring-view
subjects:
  - kind: ServiceAccount
    name: grafana-thanos
    namespace: couchbase
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: thanos
spec:
  instanceSelector:
    matchLabels:
      app: "grafana"
  valuesFrom:
    - targetPath: "secureJsonData.httpHeaderValue1"
      valueFrom:
        secretKeyRef:
          name: grafana-thanos-token
          key: token
  datasource:
    name: Thanos
    type: prometheus
    access: proxy
    isDefault: true
    url: https://thanos-querier.openshift-monitoring.svc:9091
    jsonData:
      tlsSkipVerify: true
      httpHeaderName1: Authorization
    secureJsonData:
      # The operator will replace ${token} with the value from the Secret key "token"
      httpHeaderValue1: "Bearer ${token}"
