---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster.yaml
  - buckets.yaml
  - users.yaml
  - ingress.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: couchbase
      app.kubernetes.io/component: database
      app.kubernetes.io/managed-by: argocd
